name: Ahmet
markdown: redcarpet
pygments: true
github: http://www.github.com/ahmetabdi
about: I am an developer from the UK, living in London. My tools are Ruby, Rails and RubyMotion.
urls:
    - text: twitter
      url: https://twitter.com/ahmet1up
    - text: github
      url: https://github.com/ahmetabdi
    - text: email
      url: mailto:ahmetabdi@gmail.com
