name: Simply Grey 
markdown: redcarpet
pygments: true
github: www.github.com/exaem
about: I am an independent developer from the sunny UK. I dabble in Ruby, play in C and I'm an avid systems administrator.
urls:
    - text: github
      url: https://github.com/exaem
    - text: email
      url: mailto:exaem@exaem.co.uk
